PayItForward/PayItForward/Controllers/Crear_PublicacionController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PayItForward.Models;

namespace PayItForward.Controllers
{
    public class Crear_PublicacionController : Controller
    {
        // GET: Crear_Publicacion
        Conexion miConexion = new Conexion();

        public ActionResult Index()
        {
            if (Session["UserNow"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                //traigo las categorias padre y las meto en un ViewBag
                List<Categorias> ListaCategoriasPadre = new List<Categorias>();
                ListaCategoriasPadre = miConexion.TraerCategoriasPadres();
                ViewBag.Lista = ListaCategoriasPadre;

                return View();
            }
        }

        public ActionResult Productos()
        {
            //busco las categorias hijas de la categoria padre Productos (Id=1) y las meto en un ViewBag
            List<Categorias> ListaHijas = new List<Categorias>();
            Publicacion Public = new Publicacion();
            ListaHijas = miConexion.TraerCategoriasHijas(1);
            ViewBag.CategoriasHijas = ListaHijas;
            ViewBag.Pub = Public;
            return View("CategoriasHijas");
        }

        public ActionResult Servicios()
        {
            //busco las categorias hijas de la categoria padre Servicios (Id=2) y las meto en un ViewBag
            List<Categorias> ListaHijas = new List<Categorias>();
            Publicacion Public = new Publicacion();
            ListaHijas = miConexion.TraerCategoriasHijas(2);
            ViewBag.CategoriasHijas = ListaHijas;
            ViewBag.Pub = Public;

            return View("CategoriasHijas");
        }

        public JsonResult TraerHijas(int idPadre)
        {
            //funcion llamada por ajax
            //devuelvo un array con objetos (categorias) en forma de JSON con las categorias hijas de la categoria padre seleccionada por el usuario
            List<Categorias> cates = miConexion.TraerCategoriasHijas(idPadre);
            var jsonData = Json(cates, JsonRequestBehavior.AllowGet);
            return jsonData;
        }

        public ActionResult DescripcionPublicacion(int IdCategoria)
        {
            if (Session["UserNow"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                //pongo en un ViewBag la categoria final seleccionada por el usuario
                ViewBag.CategoriaActual = miConexion.TraerNombreCategoriaPorId(IdCategoria);
                ViewBag.IdCategoriaActual = IdCategoria;

                Publicacion Publi = new Publicacion();
                return View("DescripcionPublicacion", Publi);
            }
        }

        [HttpPost]
        public ActionResult MostrarPublicacion(Publicacion Publi, int IdCategoria)
        {
            if (Session["UserNow"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                Publi.IdCategoria = Convert.ToInt32(IdCategoria);
                if (!ModelState.IsValid)
                {
                    ViewBag.CategoriaActual = IdCategoria;
                    return View("DescripcionPublicacion", Publi);
                }
                else
                {
                    if (Publi.Imagenes.Length > 3 || Publi.Imagenes[0] == null)
                    {
                        ViewBag.CategoriaActual = IdCategoria;
                        return RedirectToAction("DescripcionPublicacion", Publi);
                    }
                    else
                    {
                        // guardar las imagenes en content
                        Publi.IdUsuario = Convert.ToInt32(Session["IdUsuario"]);
                        Publi.IdPublicacion = miConexion.TraerUltimaPublicacion()+1;
                        int UltimaPublicacion = miConexion.CrearPublicacion(Publi);

                        if (Publi.Imagenes != null)
                        {
                            Publi.NombreImagen = new List<string>();
                            foreach (HttpPostedFileBase img in Publi.Imagenes)
                            {
                                if (img != null)
                                {
                                    string NuevaUbicacion = Server.MapPath("~/Content/ImagenesPublicaciones/") + UltimaPublicacion + "_" + img.FileName;
                                    img.SaveAs(NuevaUbicacion);
                                    Publi.NombreImagen.Add(img.FileName.ToString());
                                }
                            }
                        }

                        ViewBag.Publicacion = Publi;
                        List<string> listaImagenes = new List<string>();
                        foreach (HttpPostedFileBase x in Publi.Imagenes)
                        {
                            listaImagenes.Add("~/Content/ImagenesPublicaciones/" + UltimaPublicacion + "_" + x.FileName);
                        }
                        ViewBag.imagenesPublicacion = listaImagenes;

                        Usuarios user = miConexion.traerUsuarioPorId(Convert.ToInt32(Session["IdUsuario"]));
                        Session["Puntos"] = user.Puntos;

                        return View();
                    }
                }
            }
        }
    }
}

PayItForward/PayItForward/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PayItForward.Models;

namespace PayItForward.Controllers
{
    public class HomeController : Controller
    {
        Conexion miConexion = new Conexion();

        public ActionResult Index()
        {
            List<Banners> Lista = new List<Banners>();
            Lista = miConexion.TraerBanners();
            ViewBag.Banners = Lista;
            ViewBag.Contador = 0;
            return View();
        }
    }
}

PayItForward/PayItForward/Controllers/VentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PayItForward.Models;

namespace PayItForward.Controllers
{
    public class VentaController : Controller
    {
        Conexion mIConexion = new Conexion();
        // GET: Venta
        public ActionResult Index()
        {
            if (Session["UserNow"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                List<Publicacion> ListaPublicaciones = new List<Publicacion>();
                ListaPublicaciones = mIConexion.TraerTodxsLxsPublicacionos();
                int z = 0;
                do
                {
                    int IdUser = Convert.ToInt32(Session["IdUsuario"]);
                    if (ListaPublicaciones[z].IdUsuario == IdUser)
                    {
                        ListaPublicaciones.Remove(ListaPublicaciones[z]);
                        z--;
                    }
                    z++;
                } while (ListaPublicaciones.Count() > z);

                ViewBag.Publicaciones = ListaPublicaciones;
                List<string> listaImagenes = new List<string>();

                int contImg = 1;

                foreach (Publicacion Publi in ListaPublicaciones)
                {
                    foreach (String nombreImagen in Publi.NombreImagen)
                    {
                        if(contImg==1)
                        {
                            listaImagenes.Add("~/Content/ImagenesPublicaciones/" + nombreImagen);
                        }
                        contImg++;
                    }
                    contImg = 1;
                }
                ViewBag.imagenesPublicacion = listaImagenes;
                return View();
            }
        }

        public ActionResult BusquedaTexto(string texto)
        {
            if (Session["UserNow"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.HuboPublis = true;

                List<Publicacion> publicaciones = new List<Publicacion>();
                publicaciones = mIConexion.BusquedaPublicacionesPorTexto(texto);
                if (publicaciones != null)
                {
                    if (publicaciones.Count() == 0)
                    {
                        ViewBag.HuboPublis = false;
                    }
                    else
                    {
                        List<string> listaImagenes = new List<string>();
                        foreach (Publicacion publi in publicaciones)
                        {
                            listaImagenes.Add("~/Content/ImagenesPublicaciones/" + publi.NombreImagen[0]);
                        }

                        int z = 0;
                        do
                        {
                            int IdUser = Convert.ToInt32(Session["IdUsuario"]);
                            if (publicaciones[z].IdUsuario == IdUser)
                            {
                                publicaciones.Remove(publicaciones[z]);
                                z--;
                            }
                            z++;
                        } while (publicaciones.Count() > z);

                        if(publicaciones.Count() == 0)
                        {
                            ViewBag.HuboPublis = false;
                        }

                        ViewBag.imagenesPublicacion = listaImagenes;
                        ViewBag.publicaciones = publicaciones;
                    }
                }
                else
                {
                    ViewBag.HuboPublis = false;
                }
                return View("Resultadosbusqueda");
            }
        }

        public ActionResult Comprar(int id)
        {
            if (Session["UserNow"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                Publicacion publicacion = new Publicacion();
                publicacion = mIConexion.TraerPublicacionPorId(id);
                Usuarios user = new Usuarios();
                user = mIConexion.traerUsuarioPorId(Convert.ToInt32(Session["IdUsuario"]));
                if (user.Especial == true)
                {
                    mIConexion.ObtenerPublicacionEspecial(id, publicacion.IdUsuario);
                    return RedirectToAction("FinalizarCompra", publicacion);
                }
                else
                {
                    if (user.Puntos >= publicacion.Valor)
                    {
                        mIConexion.ObtenerPublicacionNoEspecial(id, user.IdUsuario, publicacion.IdUsuario);
                        user = mIConexion.traerUsuarioPorId(user.IdUsuario);
                        Session["Puntos"] = user.Puntos;

                        return RedirectToAction("FinalizarCompra", publicacion);
                    }
                    else
                    {
                        ViewBag.Mensaje = "No contas con puntos suficientes para obtener esta publicacion";
                        List<Publicacion> ListaPublicaciones = new List<Publicacion>();
                        ListaPublicaciones = mIConexion.TraerTodxsLxsPublicacionos();
                        List<string> listaImagenes = new List<string>();

                        int contImg = 1;

                        int z = 0;
                        do
                        {
                            int IdUser = Convert.ToInt32(Session["IdUsuario"]);
                            if (ListaPublicaciones[z].IdUsuario == IdUser)
                            {
                                ListaPublicaciones.Remove(ListaPublicaciones[z]);
                                z--;
                            }
                            z++;
                        } while (ListaPublicaciones.Count() > z);

                        foreach (Publicacion Publi in ListaPublicaciones)
                        {
                            foreach (String nombreImagen in Publi.NombreImagen)
                            {
                                if (contImg == 1)
                                {
                                    listaImagenes.Add("~/Content/ImagenesPublicaciones/" + nombreImagen);
                                }
                                contImg++;
                            }
                            contImg = 1;
                        }

                        ViewBag.Publicaciones = ListaPublicaciones;
                        ViewBag.imagenesPublicacion = listaImagenes;
                        return View("Index");
                    }
                }
            }
        }

        public ActionResult FinalizarCompra(Publicacion publicacion)
        {
            if (Session["UserNow"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                Usuarios user = mIConexion.traerUsuarioPorId(publicacion.IdUsuario);
                ViewBag.Mail = user.Mail;
                ViewBag.Nombre = user.Nombre;
                return View();
            }
        }

        public ActionResult BusquedaCategorias()
        {

            if (Session["UserNow"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }

        public JsonResult TraerHijas(string nombrePadre)
        {
            //funcion llamada por ajax
            //devuelvo un array con objetos (categorias) en forma de JSON con las categorias hijas de la categoria padre seleccionada por el usuario
            List<Categorias> cates = mIConexion.TraerCategoriasHijasPorNombre(nombrePadre);
            var jsonData = Json(cates, JsonRequestBehavior.AllowGet);
            return jsonData;
        }

        public JsonResult TraerPublicacionesBusquedaCategoria(string nombrePadre)
        {
            //funcion llamada por ajax
            //devuelvo un array con objetos (publicaciones) en forma de JSON de la categorias hija seleccionada por el usuario
            List<Publicacion> pub = mIConexion.TraerPublicacionesBusquedaCategoria(nombrePadre);
            List<Publicacion> pub2 = mIConexion.TraerPublicacionesPorIdCategoria(mIConexion.traerIDCategoriaPorNombre(nombrePadre));
            foreach(Publicacion X in pub2)
            {
                pub.Add(X);
            }

            int z = 0;
            do
            {
                int IdUser = Convert.ToInt32(Session["IdUsuario"]);
                if (pub[z].IdUsuario == IdUser)
                {
                    pub.Remove(pub[z]);
                    z--;
                }
                z++;
            } while (pub.Count() > z);

            var jsonData = Json(pub, JsonRequestBehavior.AllowGet);
            return jsonData;
        }
    }
}

PayItForward/PayItForward/Views/Home/Index.cshtml
@using PayItForward.Models

@{
    ViewBag.Title = "Home Page";
}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <style type="text/css" style="display: none !important;">
        .w3-left, .w3-right, .w3-badge {
            cursor: pointer;
        }

        .w3-badge {
            height: 13px;
            width: 13px;
            padding: 0;
        }

        .textWithBlurredBg img {
            width: 75%;
            max-width: 1000px;
            border-radius: 4px;
            transition: .3s;
        }

        .textWithBlurredBg:hover img {
            filter: blur(2px) brightness(60%);
        }

        .contenedorImagenes {
            margin-top: 25px;
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 75%;
        }

        .contenedorTexto {
            position: absolute;
            z-index: 10;
            color: #fff;
            text-align: center;
            width: 100%;
            opacity: 0;
            transition: .3s;
            top: 50%;
            transform: translateY(50%);
        }

        .textWithBlurredBg :hover {
            opacity: 1;
        }

        .mySlides {
            display: none;
        }

        .banner {
            display: inline-block;
        }

        .banner-lg {
            width: 75%;
        }

        .banner {
            height: 257px;
            padding: 0;
            margin: 0;
        }

        .last {
            margin-top: 200px;
        }
    </style>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#slideshow > div:gt(0)").hide();
            setInterval(function () {
                $('#SlideshowImages > div:first').fadeOut(1000).next().fadeIn(1000).end().appendTo('#SlideshowImages');
            }, 3000);
        });

        var myIndex = 0;
        carousel();

        function carousel() {
            var i;
            var x = document.getElementsByClassName("mySlides");
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }
            myIndex++;
            if (myIndex > x.length) { myIndex = 1 }
            x[myIndex - 1].style.display = "block";
            setTimeout(carousel, 5000); // Change image every 5 seconds
        }
    </script>
</head>
<body>
    <div style="margin-top: 400px">
        <!-- Slider -->
        <div class="w3-content w3-section">
            @foreach (Banners X in ViewBag.Banners)
            {
                <img src="~/Content/SliderHome/@X.Imagen" class="mySlides" style="width:940px">
            }
        </div>

        <div class="row">
            <div class="banner banner-lg">
                <a href="#" class="textWithBlurredBg">
                    <div style="position:relative">
                        <div style="position:absolute">
                            <img class="img-fluid" src="~/Content/BannersHome/infoUtil.png" style="width:100%">
                        </div>
                        <div class="contenedorTexto">
                            <h2>Informacion</h2>
                            <h3>Hace click aca para informarte</h3>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="banner banner-lg">
                <a href="@Url.Action("Index","Crear_Publicacion")" class="textWithBlurredBg">
                    <div style="position:relative">
                        <div style="position:absolute">
                            <img class="img-fluid" src="~/Content/BannersHome/CrearPublicacion.png" style="width:100%">
                        </div>
                        <div class="contenedorTexto">
                            <h2>Crear publicacion</h2>
                            <h3>Hacé click acá para contribuir</h3>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        <div class="row" style="margin-top: 25px">
            <div class="banner banner-lg last">
                <a href="@Url.Action("Index","Venta")" class="textWithBlurredBg">
                    <div style="position:relative">
                        <div style="position:absolute">
                            <img class="img-fluid" src="~/Content/BannersHome/VerPublicaciones.png" style="width:100%">
                        </div>
                        <div class="contenedorTexto">
                            <h2>Ver publicaciones</h2>
                            <h3>Hacé click acá para ver las publicaciones de otros usuarios</h3>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</body>

PayItForward/PayItForward/Views/Home/Informacion.cshtml
@{
    ViewBag.Title = "Informacion";
}

<h2>Informacion</h2>