PayItForward/PayItForward/Controllers/BMPublicacionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PayItForward.Models;

namespace PayItForward.Controllers
{
    public class BMPublicacionesController : Controller
    {
        Conexion miConexion = new Conexion();

        // GET: BMPublicaciones
        public ActionResult VerPublicaciones()
        {
            if (Session["UserNow"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                List<Publicacion> ListaPublicaciones = new List<Publicacion>();
                //traigo las publicaciones del usuario actual y las pongo en un ViewBag
                ListaPublicaciones = miConexion.TraerPublicacionesPorUsuario(Convert.ToInt32(Session["IdUsuario"]));
                ViewBag.Lista = ListaPublicaciones;

                return View();
            }
        }

        public ActionResult BMPublicacion(string Accion, int Id)
        {
            if (Session["UserNow"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                if (Accion == "Eliminar")
                {
                    //elimino la publicacion
                    miConexion.EliminarPublicacion(Id);
                }
                else if (Accion == "Modificar" || Accion == "Ver")
                {
                    //traigo la publicacion seleccionada en la View "VerPublicaciones"
                    Publicacion X = miConexion.TraerPublicacionPorId(Id);
                    ViewBag.Accion = Accion;

                    List<string> listaImagenes = new List<string>();
                    foreach (String x in X.NombreImagen)
                    {
                        if (x != "")
                        {
                            listaImagenes.Add("~/Content/ImagenesPublicaciones/" + x);
                        }
                    }
                    ViewBag.imagenesPublicacion = listaImagenes;

                    return View(X);
                }
                return RedirectToAction("VerPublicaciones");
            }
        }


        public ActionResult editarPublicacion(Publicacion x)
        {
            if (Session["UserNow"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                if (!ModelState.IsValid)
                {
                    ViewBag.CategoriaActual = x.IdCategoria;
                    ViewBag.Accion = "Modificar";
                    return View("BMPublicacion", x);
                }
                else
                {
                    if (x.Imagenes[0] == null)
                    {
                        Publicacion publi = new Publicacion();
                        publi = miConexion.TraerPublicacionPorId(x.IdPublicacion);

                        publi.Titulo = x.Titulo;
                        publi.Valor = x.Valor;
                        publi.Descripcion = x.Descripcion;
                        publi.Ubicacion = x.Ubicacion;
                        /*if (publi.NombreImagen[0] != "")
                        {
                            x.NombreImagen.Add
                        }
                        if (publi.NombreImagen[1] != "")
                        {
                            x.NombreImagen.Add(publi.NombreImagen[1]);
                        }
                        if (publi.NombreImagen[2] != "")
                        {
                            x.NombreImagen.Add(publi.NombreImagen[2]);
                        }*/
                        miConexion.ModificarPublicacionSinImagen(publi);
                        foreach (HttpPostedFileBase img in x.Imagenes)
                        {
                            if (img != null)
                            {
                                string NuevaUbicacion = Server.MapPath("~/Content/ImagenesPublicaciones/") + x.IdPublicacion + "_" + img.FileName;
                                img.SaveAs(NuevaUbicacion);
                            }
                        }
                    }
                    else
                    {
                        miConexion.ModificarPublicacionConImagen(x);
                        foreach (HttpPostedFileBase img in x.Imagenes)
                        {
                            if (img != null)
                            {
                                string NuevaUbicacion = Server.MapPath("~/Content/ImagenesPublicaciones/") + x.IdPublicacion + "_" + img.FileName;
                                img.SaveAs(NuevaUbicacion);
                            }
                        }
                    }

                    return RedirectToAction("VerPublicaciones");
                }
            }
        }
    }
}

PayItForward/PayItForward/Controllers/Crear_PublicacionController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PayItForward.Models;

namespace PayItForward.Controllers
{
    public class Crear_PublicacionController : Controller
    {
        // GET: Crear_Publicacion
        Conexion miConexion = new Conexion();

        public ActionResult Index()
        {
            if (Session["UserNow"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                //traigo las categorias padre y las meto en un ViewBag
                List<Categorias> ListaCategoriasPadre = new List<Categorias>();
                ListaCategoriasPadre = miConexion.TraerCategoriasPadres();
                ViewBag.Lista = ListaCategoriasPadre;

                return View();
            }
        }

        public ActionResult Productos()
        {
            //busco las categorias hijas de la categoria padre Productos (Id=1) y las meto en un ViewBag
            List<Categorias> ListaHijas = new List<Categorias>();
            Publicacion Public = new Publicacion();
            ListaHijas = miConexion.TraerCategoriasHijas(1);
            ViewBag.CategoriasHijas = ListaHijas;
            ViewBag.Pub = Public;
            return View("CategoriasHijas");
        }

        public ActionResult Servicios()
        {
            //busco las categorias hijas de la categoria padre Servicios (Id=2) y las meto en un ViewBag
            List<Categorias> ListaHijas = new List<Categorias>();
            Publicacion Public = new Publicacion();
            ListaHijas = miConexion.TraerCategoriasHijas(2);
            ViewBag.CategoriasHijas = ListaHijas;
            ViewBag.Pub = Public;

            return View("CategoriasHijas");
        }

        public JsonResult TraerHijas(int idPadre)
        {
            //funcion llamada por ajax
            //devuelvo un array con objetos (categorias) en forma de JSON con las categorias hijas de la categoria padre seleccionada por el usuario
            List<Categorias> cates = miConexion.TraerCategoriasHijas(idPadre);
            var jsonData = Json(cates, JsonRequestBehavior.AllowGet);
            return jsonData;
        }

        public ActionResult DescripcionPublicacion(int IdCategoria)
        {
            if (Session["UserNow"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                //pongo en un ViewBag la categoria final seleccionada por el usuario
                ViewBag.CategoriaActual = miConexion.TraerNombreCategoriaPorId(IdCategoria);
                ViewBag.IdCategoriaActual = IdCategoria;

                Publicacion Publi = new Publicacion();
                return View("DescripcionPublicacion", Publi);
            }
        }

        [HttpPost]
        public ActionResult MostrarPublicacion(Publicacion Publi, int IdCategoria)
        {
            if (Session["UserNow"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                Publi.IdCategoria = Convert.ToInt32(IdCategoria);
                if (!ModelState.IsValid)
                {
                    ViewBag.CategoriaActual = IdCategoria;
                    return View("DescripcionPublicacion", Publi);
                }
                else
                {
                    if (Publi.Imagenes.Length > 3 || Publi.Imagenes[0] == null)
                    {
                        ViewBag.CategoriaActual = IdCategoria;
                        return RedirectToAction("DescripcionPublicacion", Publi);
                    }
                    else
                    {
                        // guardar las imagenes en content
                        Publi.IdUsuario = Convert.ToInt32(Session["IdUsuario"]);
                        Publi.IdPublicacion = miConexion.TraerUltimaPublicacion()+1;
                        int UltimaPublicacion = miConexion.CrearPublicacion(Publi);

                        if (Publi.Imagenes != null)
                        {
                            Publi.NombreImagen = new List<string>();
                            foreach (HttpPostedFileBase img in Publi.Imagenes)
                            {
                                if (img != null)
                                {
                                    string NuevaUbicacion = Server.MapPath("~/Content/ImagenesPublicaciones/") + UltimaPublicacion + "_" + img.FileName;
                                    img.SaveAs(NuevaUbicacion);
                                    Publi.NombreImagen.Add(img.FileName.ToString());
                                }
                            }
                        }

                        ViewBag.Publicacion = Publi;
                        List<string> listaImagenes = new List<string>();
                        foreach (HttpPostedFileBase x in Publi.Imagenes)
                        {
                            listaImagenes.Add("~/Content/ImagenesPublicaciones/" + UltimaPublicacion + "_" + x.FileName);
                        }
                        ViewBag.imagenesPublicacion = listaImagenes;

                        Usuarios user = miConexion.traerUsuarioPorId(Convert.ToInt32(Session["IdUsuario"]));
                        Session["Puntos"] = user.Puntos;

                        return View();
                    }
                }
            }
        }
    }
}

PayItForward/PayItForward/Views/Crear_Publicacion/CategoriasHijas.cshtml
@using PayItForward.Models;

@{
    ViewBag.Title = "Productos";
}

<head>
    <link href="~/Styles/ProgressBar.css" rel="stylesheet" />
    <script>
        function Hijas(cat, nom) {
            $.ajax({
                url: '@Url.Action("TraerHijas", "Crear_Publicacion")',
                type: "post",
                dataType: "html",
                contentType: 'application/json; charset=utf-8',
                data: JSON.stringify({ idPadre: cat }),
                success: function (cates) {
                    var thtml = '';
                    var obj = JSON.parse(cates);
                    if (obj.length == 0) {
                        //si trae vacio el JSON con las categorias hijas, mando al usuario a proxima view (DescripcionPublicacion) con la categoria seleccionada
                        Final(cat);
                    } else {
                        for (var i = 0; i < obj.length; i++) {
                            var cate = obj[i];
                            thtml += "<li value='" + cate.IdCategoria + "' onclick = 'Hijas(" + cate.IdCategoria + ",\"" + cate.Nombre + "\");' >" + cate.Nombre + "</li>";
                        }
                        $("#categorias").html(thtml)
                        $("#seguimiento").append(" > " + nom);
                    }
                },
                error: function () {
                    alert("Ha ocurrido un error");
                }
            });
        }
        function Final(cat) {
            var url = '@Url.Action("DescripcionPublicacion", "Crear_Publicacion", new { IdCategoria = "__id__",  Publi = ViewBag.Pub })';
            window.location.href = url.replace('__id__', cat);
        }
    </script>
    <style>
        li {
            padding: 10px 5px 10px;
            cursor: pointer;
        }

            li :hover {
                background-color: lightslategray;
            }

        hr {
            margin: 0px;
            padding: 0px;
        }
    </style>
</head>

<body>
    <div style="background-color:white">
        <!--PROGRESO-->
        <div style="background-color:white;height:98px">
            <ol class="progress progress--medium">
                <li class="is-active" data-step="1">
                    Seleccionar categoria
                </li>
                <li data-step="2" class=" progress__last">
                    Editar publicacion
                </li>
            </ol>
        </div>
        <hr />
        <div style="background-color: white">
            <div style="margin-left: 10px; margin-top: 5px; padding-bottom: 10px">
                <p style="font-size: 20px; margin-bottom: 5px">Categorias especificas</p>
                <p style="font-size: 15px; margin-bottom: 0px; margin-top: 0px">Navega las categorias en el listado y elige una</p>
                <br />
                <p id="seguimiento" style="font-size: 15px; margin-bottom: 0px; margin-top: 0px">Inicio</p>
            </div>
        </div>
        <hr style="margin: 0px">
        <div style="background-color: white">
            <ul style="list-style:none; padding: 20px 10px 20px; margin: 0; padding-top: 10px; padding-bottom: 10px" id="categorias">
                @foreach (Categorias X in ViewBag.CategoriasHijas)
                {
                    <li value="@X.IdCategoria" onclick="Hijas(@X.IdCategoria, '@X.Nombre');">
                        @X.Nombre
                    </li>
                }
            </ul>
            <input type="hidden" value="@ViewBag.Pub" name="Publi" />
        </div>
    </div>
</body>

PayItForward/PayItForward/Views/Crear_Publicacion/DescripcionPublicacion.cshtml
@using PayItForward.Models
@model Publicacion
@{
    ViewBag.Title = "DescripcionPublicacion";
}


<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href="~/Styles/ProgressBar.css" rel="stylesheet" />
    <style>
        .validation {
            color: red;
            font-size: 18px;
        }

        .inputDetalles {
            margin-right: 0px;
            margin-left: 25px;
            margin-bottom: -20px;
            width: 100%;
        }

        .labelDetalles {
            margin-left: 25px;
        }

        label {
            font-weight: normal !important;
        }

        input[type=submit] {
            margin-left: 25px;
            margin-bottom: 25px;
            background-color: white;
            padding-top: 10px;
            padding-bottom: 10px;
            padding-left: 40px;
            padding-right: 40px;
            border-radius: 5px;
            border-color: grey;
        }
    </style>
    <script>
        $(function () {
            $("input[type='submit']").click(function () {

                var $fileUpload = $("input[type='file']");
                if (parseInt($fileUpload.get(0).files.length) > 3) {
                    alert("Selecciona hasta un maximo de 3 imàgenes");
                }
            });
        });
    </script>
</head>
<body>
    <div style="background-color:white;margin-top:100px">
        <!--PROGRESO-->
        <div style="background-color:white;height:66px">
            <ol class="progress progress--medium">
                <li class="is-complete" data-step="1">
                    Seleccionar categoria
                </li>
                <li data-step="2" class="is-active progress__last">
                    Editar publicacion
                </li>
            </ol>
        </div>
        <hr />
        <div style="background-color:white">
            <p style="text-align:center">La categoria actual es @ViewBag.CategoriaActual</p> <!--CAMBIAR POR EL RECORRIDO DE LAS CATEGORIAS-->

            <hr />

            <div style="background-color: white">
                <div style="margin-left: 10px; margin-top: 5px; padding-bottom: 10px">
                    <p style="font-size: 20px; margin-bottom: 5px">Publicacion</p>
                    <p style="font-size: 15px; margin-bottom: 0px; margin-top: 0px">Describi los detalles de tu producto/servicio</p>
                    <br />
                </div>
            </div>
           

            <form method="post" action="@Url.Action("MostrarPublicacion", "Crear_Publicacion")" id="formulario" enctype="multipart/form-data">
                <div style="display:inline-block">
                    @Html.TextBoxFor(x => x.Imagenes, new { type = "file", Multiple = "Multiple", Name = "Imagenes", id = "file", Style = "float:left", Class = "w3-input inputDetalles" })
                </div> <br /> <br />
                <label class="labelDetalles" for="file">Imagenes @Html.ValidationMessageFor(x => x.Imagenes, null, new { @class = "validation" })</label>

                @Html.TextBoxFor(x => x.Valor, new { Type = "number", Class = "w3-input inputDetalles", Name = "Valor" }) <br />
                <label class="labelDetalles" for="Valor">Valor @Html.ValidationMessageFor(x => x.Valor, null, new { @class = "validation" })</label>

                @Html.TextBoxFor(x => x.Titulo, new { Class = "w3-input inputDetalles", Name = "Titulo" }) <br />
                <label class="labelDetalles" for="Titulo">Titulo @Html.ValidationMessageFor(x => x.Titulo, null, new { @class = "validation" })</label>

                @Html.TextBoxFor(x => x.Descripcion, new { Class = "w3-input inputDetalles", Name = "Descripcion" }) <br />
                <label class="labelDetalles" , for="Descripcion">Descripcion @Html.ValidationMessageFor(x => x.Descripcion, null, new { @class = "validation" })</label>

                @Html.TextBoxFor(x => x.Ubicacion, new { Class = "w3-input inputDetalles", Name = "Ubicacion" }) <br />
                <label class="labelDetalles" for="Ubicacion">Ubicacion @Html.ValidationMessageFor(x => x.Ubicacion, null, new { @class = "validation" })</label>

                <input type="hidden" value="@ViewBag.IdCategoriaActual" name="IdCategoria" />
                <br /><br /><br />

                <input type="submit" value="Continuar" />
            </form>
        </div>
    </div>
</body>

PayItForward/PayItForward/Views/Crear_Publicacion/Index.cshtml
@using PayItForward.Models;

@{
    ViewBag.Title = "Index";
}

<head>
    <link href="~/Styles/ProgressBar.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <style>
        .Categorias_Productos {
            border: 2px solid lightgrey;
            width: 190px;
            padding-top: 50px;
            padding-bottom: 50px;
            padding-left: 62px;
            padding-right: 62px;
        }

        .Categorias_Servicios {
            border: 2px solid lightgrey;
            width: 190px;
            padding-top: 50.5px;
            padding-bottom: 50px;
            padding-left: 50px;
            padding-right: 50px;
        }

        .Productos :hover {
            border: 2px solid green;
        }

        .Servicios :hover {
            border: 2px solid red;
        }

        form {
            margin-left: auto;
            margin-right: auto;
            display: inline-block;
        }

        .contenedor-categorias {
            margin-left: auto;
            margin-right: auto;
            text-align: center;
        }

        .botones {
            padding: 25px 25px 25px 25px;
        }
    </style>
</head>

<body>
    <div style="background-color:white">
        <!--PROGRESO-->
        <div style="background-color:white;height:66px">
            <ol class="progress progress--medium">
                <li class="is-active" data-step="1">
                    Seleccionar categoria
                </li>
                <li data-step="2" class=" progress__last">
                    Editar publicacion
                </li>
            </ol>
        </div>

        <hr />

        <!--TITULO-->
        <div style="background-color: white">
            <div style="margin-left: 10px; margin-top: 5px; padding-bottom: 10px">
                <p style="font-size: 20px; margin-bottom: 5px">Categorias generales</p>
                <p style="font-size: 15px; margin-bottom: 0px; margin-top: 0px">Selecciona una de las categorias principales</p>
            </div>
        </div>

        <!--DIV CENTRADO: contiene las dos categorias padre-->
        <div class="contenedor-categorias">
            @foreach (Categorias X in ViewBag.Lista)
            {
                <form action="@Url.Action(X.Nombre, "Crear_Publicacion")" class="@X.Nombre">
                    <input type="image" class="w3-btn botones" value="@X.Nombre" src="~/Content/ImagenesCategoria/@X.Imagen" id="@X.Nombre">
                </form>
            }
        </div>
    </div>
</body>

PayItForward/PayItForward/Views/Crear_Publicacion/MostrarPublicacion.cshtml
@using PayItForward.Models

@{
    ViewBag.Title = "VistaPrevia";
}

<head>
    <link rel="stylesheet" href="Styles/linearicons.css">
    <link rel="stylesheet" href="Styles/font-awesome.min.css">
    <link rel="stylesheet" href="Styles/themify-icons.css">
    <link rel="stylesheet" href="Styles/bootstrap.css">
    <link rel="stylesheet" href="Styles/owl.carousel.css">
    <link rel="stylesheet" href="Styles/nice-select.css">
    <link rel="stylesheet" href="Styles/nouislider.min.css">
    <link rel="stylesheet" href="Styles/ion.rangeSlider.css" />
    <link rel="stylesheet" href="Styles/ion.rangeSlider.skinFlat.css" />
    <link rel="stylesheet" href="Styles/main.css">

    <style>
        .cd-item-wrapper li {
            position: absolute;
            top: 0;
            left: 25%;
            width: 50%;
            opacity: 0;
            transform: translateX(200%) scale(0.7);
        }

            .cd-item-wrapper li.selected {
                /* selected item */
                position: relative;
                opacity: 1;
                transform: translateX(0) scale(1.3);
            }

            .cd-item-wrapper li.move-right {
                /* item on right - preview visible */
                transform: translateX(100%) scale(0.7);
                opacity: 0.3;
            }

            .cd-item-wrapper li.move-left {
                /* item on left - preview visible */
                transform: translateX(-100%) scale(0.7);
                opacity: 0.3;
            }

            .cd-item-wrapper li.hide-left {
                /* items hidden on the left */
                transform: translateX(-200%) scale(0.7);
            }

        @@media only screen and (min-width: 1048px) {
            .cd-item-wrapper li.move-left,
            .cd-item-wrapper li.move-right {
                /* hide preview items */
                opacity: 0;
            }

            .cd-item-wrapper li.focus-on-left {
                /* class added to the .selected and .move-right items when user hovers over the .move-left item (item preview on the left) */
                transform: translateX(3%) scale(1.25);
            }

                .cd-item-wrapper li.focus-on-left.move-right {
                    transform: translateX(103%) scale(0.7);
                }

            .cd-item-wrapper li.focus-on-right {
                /* class added to the .selected and .move-left items when user hovers over the .move-right item (item preview on the right) */
                transform: translateX(-3%) scale(1.25);
            }

                .cd-item-wrapper li.focus-on-right.move-left {
                    transform: translateX(-103%) scale(0.7);
                }

            .cd-item-wrapper li.hover {
                /* class added to the preview items (.move-left or .move-right) when user hovers over them */
                opacity: 1;
            }

                .cd-item-wrapper li.hover.move-left {
                    transform: translateX(-97%) scale(0.75);
                }

                .cd-item-wrapper li.hover.move-right {
                    transform: translateX(97%) scale(0.75);
                }
        }
    </style>
</head>
<body>
    <div style="background-color:white">
        <div>
            <!--CATEGORIA-->
            La categoria actual es @ViewBag.Publicacion.IdCategoria
        </div> <hr />

        <div>
            <!--IMAGENES-->
            <ul class="cd-gallery">
                <li>
                    <ul class="cd-item-wrapper">

                        @foreach (String x in ViewBag.imagenesPublicacion)
                        {
                            <li class="selected">
                                <img src="@Url.Content(x)" alt="Preview image" style="width:100px;height:100px">
                            </li>
                        }

                    </ul> <!-- cd-item-wrapper -->
                </li>
            </ul> <!-- cd-gallery -->
        </div>
        <div>
            <!--INFO: titulo, precio, ubicacion, etc.-->
            <!--TITULO DESCRIPCION-->
            <div class="col-lg-5 offset-lg-1">
                <div class="s_product_text">
                    <h3>Titulo: @ViewBag.Publicacion.Titulo</h3>
                    <h2>Valor: @ViewBag.Publicacion.Valor</h2>
                    <ul class="list">
                        <li><a class="active" href="#"><span>Categoria</span> : @ViewBag.Publicacion.IdCategoria</a></li> <!--HECER QUE EL LINK VAYA A BUSCAR PRODUCTOS DE ESA CATEGORIA-->
                        <li><a href="#"><span>Ubicacion</span> : @ViewBag.Publicacion.Ubicacion</a></li> <!--LINK?-->
                    </ul>
                    <p>
                        @ViewBag.Publicacion.Descripcion
                    </p>
                    <div class="product_count">
                        <!--HECER BOTONES DE AGREGAR A CARRO Y LIKE-->
                        
                    </div>
                    <b><a href="@Url.Action("VerPublicaciones", "BMPublicaciones")">Ver Publicaciones</a></b>
                </div>
            </div>
        </div>

        <div>
            <!--QA?-->

        </div>
        
    </div>
    

</body>




<!--
Titulo: @ViewBag.Pub
<!--
Titulo: @ViewBag.Publicacion.Titulo <br />
IdCategoria: @ViewBag.Publicacion.IdCategoria <br />
IdUsuario: @ViewBag.Publicacion.IdUsuario <br />
Aprobada: @ViewBag.Publicacion.Aprobada <br />
Valor: @ViewBag.Publicacion.Valor <br />
Desc: @ViewBag.Publicacion.Descripcion <br />
Likes: @ViewBag.Publicacion.Likes <br />
Ubicacion: @ViewBag.Publicacion.Ubicacion <br />
-->

PayItForward/PayItForward/Views/Crear_Publicacion/Productos.cshtml
@using PayItForward.Models;

@{
    ViewBag.Title = "Productos";
}

<head>
    <!--HACER jquery para Final();-->
    <script>
        function Final(cat) {
            $.ajax({
                    url: '@Url.Action("TraerHijas", "Crear_Publicacion")',
                    type: "post",
                    dataType: "html",
                    contentType: 'application/json; charset=utf-8',
                    data: JSON.stringify({ Id: cat }), //add parameter
                    success: function (data) {
                        //success
                        //var objeto = JSON.parse(resultado);
                    },
                    error: function () {
                        alert("Ha ocurrido un error");
                    }
                });
        }
    </script>
</head>

<body>
    <!--DIV CENTRADO-->
    <div>
        <!--LISTA: subcategoria 1-->
        <form action="@Url.Action("DescripcionPublicacion", "Crear_Publicacion")">
            <div>
                <select name="IdCategoria">
                    @foreach (Categorias X in ViewBag.CategoriasHijas)
                    {
                        <option value="@X.IdCategoria" onclick="Final(@X.IdCategoria);">
                            @X.Nombre
                        </option>
                    }
                </select>
            </div>

            <input type="submit" value="fin" />
        </form>
    </div>
</body>